# Generated by Django 5.2.3 on 2026-04-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_concepts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a unique image for this item. This will be stored on Dropbox.', null=True, upload_to='images/%Y/%m/')),
                ('static_image_path', models.CharField(blank=True, help_text="Path to a static image (e.g., 'portfolio/images/hero.jpg'). This is faster and overrides the uploaded image.", max_length=255, null=True)),
                ('is_homepage_featured', models.BooleanField(default=False, help_text="Check this to feature this item in the 'Knowledge Hub' on the homepage.")),
                ('seo_title', models.CharField(blank=True, help_text="SEO Title for the recommendation's detail page.", max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta Description for the detail page.', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Meta Keywords for the detail page.', max_length=255, null=True)),
                ('title', models.CharField(help_text='The main title of the bootcamp/guide.', max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('level', models.CharField(default='beginner', help_text='e.g., Beginner, Junior, Intermediate', max_length=50)),
                ('target_skill', models.CharField(blank=True, help_text='e.g., Python, Django, React', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Short summary.')),
                ('long_description', models.TextField(blank=True, help_text='Long marketing description.')),
                ('is_published', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DS', 'Data Science'), ('WEB', 'Python & Django'), ('TECH', 'General Tech')], default='TECH', max_length=10)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BootcampWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(help_text="e.g., 'Week 1: Python Fundamentals'", max_length=250)),
                ('focus', models.TextField(blank=True, help_text='The technical learning goal for this week.')),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='ai_concepts.techbootcamp')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('bootcamp', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='BootcampDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='Day 1-7')),
                ('title', models.CharField(help_text="e.g., 'Understanding For-Loops'", max_length=250)),
                ('theory_lesson', models.TextField(blank=True, help_text='The concept explained. Supports Markdown.')),
                ('coding_exercise', models.TextField(blank=True, help_text='A practical code snippet or challenge. Supports Markdown.')),
                ('real_world_application', models.TextField(blank=True, help_text='How this is used in actual apps. Supports Markdown.')),
                ('mindset_focus', models.TextField(blank=True, help_text='A tip for debugging, imposter syndrome, or focus.')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='ai_concepts.bootcampweek')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('week', 'day_number')},
            },
        ),
    ]
