# Generated by Django 5.2.3 on 2026-04-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_concepts', '0002_techbootcamp_bootcampweek_bootcampday'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampday',
            name='is_rest_day',
            field=models.BooleanField(default=False, help_text='Check if this is a consolidation/rest day.'),
        ),
    ]
