# Generated by Django 5.2.3 on 2026-04-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.CharField(help_text='Displayed on the card view.', max_length=255)),
                ('description', models.TextField(help_text='Full details. Markdown is supported.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price (GBP £)', max_digits=6, null=True)),
                ('cover_image', models.URLField(blank=True, help_text='URL to the cover image', max_length=500, null=True)),
                ('external_buy_url', models.URLField(blank=True, help_text='If this is a real product, paste the Stripe/Checkout URL from your main PT site here.', max_length=500)),
                ('related_affiliate_product_name', models.CharField(blank=True, max_length=255)),
                ('related_affiliate_link', models.URLField(blank=True)),
                ('affiliate_pitch', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
