# Generated by Django 5.2.3 on 2026-04-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a unique image for this item. This will be stored on Dropbox.', null=True, upload_to='images/%Y/%m/')),
                ('static_image_path', models.CharField(blank=True, help_text="Path to a static image (e.g., 'portfolio/images/hero.jpg'). This is faster and overrides the uploaded image.", max_length=255, null=True)),
                ('is_homepage_featured', models.BooleanField(default=False, help_text="Check this to feature this item in the 'Knowledge Hub' on the homepage.")),
                ('seo_title', models.CharField(blank=True, help_text="SEO Title for the recommendation's detail page.", max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta Description for the detail page.', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Meta Keywords for the detail page.', max_length=255, null=True)),
                ('title', models.CharField(help_text='The main title of the bootcamp/guide.', max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('level', models.CharField(default='beginner', help_text='e.g., Beginner, Junior, Intermediate', max_length=50)),
                ('target_skill', models.CharField(blank=True, help_text='e.g., Python, Django, React', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Short summary.')),
                ('long_description', models.TextField(blank=True, help_text='Long marketing description.')),
                ('is_published', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DS', 'Data Science'), ('WEB', 'Python & Django'), ('TECH', 'General Tech')], default='TECH', max_length=10)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="FontAwesome class, e.g., 'fab fa-python' or 'fas fa-server'", max_length=100)),
                ('category', models.CharField(choices=[('BACKEND', 'Backend Architecture'), ('FRONTEND', 'Frontend & UI'), ('DEVOPS', 'DevOps & Tools'), ('API', 'API & Data Handling'), ('LEARNING', 'Learning Resources'), ('DATABASE', 'Database'), ('DEPLOYMENT', 'Deployment & Hosting'), ('DESIGN', 'Design & Assets'), ('LIBRARY', 'Key Python Libraries')], max_length=50)),
                ('description', models.CharField(blank=True, help_text="Short tagline, e.g. 'High-performance REST framework'", max_length=255)),
                ('is_key_library', models.BooleanField(default=False, help_text="Check this to feature it in the 'Libraries & Ecosystem' section.")),
                ('usage_explanation', models.TextField(blank=True, help_text='Technical details on how this library is utilized in this project. (Supports Markdown/HTML)')),
                ('doc_link', models.URLField(blank=True, help_text='Link to official documentation.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BootcampWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(help_text="e.g., 'Week 1: Python Fundamentals'", max_length=250)),
                ('focus', models.TextField(blank=True, help_text='The technical learning goal for this week.')),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='case_study.techbootcamp')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('bootcamp', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='High-level summary of the feature.')),
                ('challenge', models.TextField(help_text='The Problem: Why was this difficult?')),
                ('solution', models.TextField(help_text='The Fix: How did you solve it technically?')),
                ('demo_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('technology_used', models.ManyToManyField(related_name='features', to='case_study.techskill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BootcampDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='Day 1-7')),
                ('title', models.CharField(help_text="e.g., 'Understanding For-Loops'", max_length=250)),
                ('theory_lesson', models.TextField(blank=True, help_text='The concept explained. Supports Markdown.')),
                ('coding_exercise', models.TextField(blank=True, help_text='A practical code snippet or challenge. Supports Markdown.')),
                ('real_world_application', models.TextField(blank=True, help_text='How this is used in actual apps. Supports Markdown.')),
                ('mindset_focus', models.TextField(blank=True, help_text='A tip for debugging, imposter syndrome, or focus.')),
                ('is_rest_day', models.BooleanField(default=False, help_text='Check if this is a consolidation/rest day.')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='case_study.bootcampweek')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('week', 'day_number')},
            },
        ),
    ]
