# Generated by Django 5.2.3 on 2026-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techskill',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence & LLMs'), ('BACKEND', 'Backend Architecture'), ('FRONTEND', 'Frontend & UI'), ('DEVOPS', 'DevOps & CI/CD'), ('DATABASE', 'Database & Caching'), ('LIBRARY', 'Key Python Libraries')], max_length=50),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='doc_link',
            field=models.URLField(blank=True, help_text='Link to official docs.'),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='icon_class',
            field=models.CharField(help_text="FontAwesome class, e.g., 'fa-brands fa-python' or 'fa-solid fa-server'", max_length=100),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='is_key_library',
            field=models.BooleanField(default=False, help_text='Feature this in the Ecosystem section.'),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='usage_explanation',
            field=models.TextField(blank=True, help_text='How this is utilized in this project.'),
        ),
    ]
