# Generated by Django 5.2.3 on 2026-04-06 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('merchant', models.CharField(help_text='e.g., Rogue Fitness, Amazon', max_length=150)),
                ('merchant_product_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_url', models.URLField(max_length=1024)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('is_in_stock', models.BooleanField(db_index=True, default=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-is_in_stock', 'title'],
            },
        ),
    ]
